SELECT DISTINCT BRANCH.NUMBER_BR FROM BRANCH,CUSTOMER WHERE BRANCH.NUMBER_BR NOT IN (SELECT CUSTOMER.NUMBER_BR FROM CUSTOMER);

SELECT DISTINCT BRANCH.NUMBER_BR FROM BRANCH,EMPLOYEE WHERE BRANCH.NUMBER_BR NOT IN (SELECT EMPLOYEE.NUMBER_BR FROM EMPLOYEE);

SELECT TOP (1) EMPLOYEE.NAME,LOAN.ID_, COUNT(*) AS Loans_num
  FROM LOAN INNER JOIN EMPLOYEE ON LOAN.ID_=EMPLOYEE.ID_
  GROUP BY LOAN.ID_,EMPLOYEE.NAME
  ORDER BY loans_num DESC ;


  SELECT Top (1) PROVIDER.SSN As Customer_SSN, COUNT(PROVIDER.SSN) AS Loans_num
  FROM LOAN INNER JOIN  PROVIDER ON PROVIDER.LOAN_NUM = LOAN.LOAN_NUM
  GROUP BY PROVIDER.SSN
  ORDER BY loans_num DESC ;